environement:
  dataset_path: path to your dataset
  feutures_path: path to stock featuress
  Ovveride_modele : False

modele:
  image_size : 224
  feutures_shape : 1024

PCA:
  n_components : 128

Annoy:
  n_tree : 15


