environement:
  dataset_path: C:\Users\Hp\Desktop\CBIR-New-Search-Engine-Approach\dataset\training_set
  feutures_path: C:\Users\Hp\Desktop\CBIR-New-Search-Engine-Approach\database
  Ovveride_modele : False

modele:
  image_size : 224
  feutures_shape : 1024

PCA:
  n_components : 128

Annoy:
  n_tree : 15


